name: Build and deploy Node.js app to Azure Web App - immoleaf-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install dependencies and build
        run: |
          cd backend
          npm install
          npm run build || echo "No build step"

      - name: Prepare deployment package
        run: |
          cd backend
          zip -r ../backend.zip ./*

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: deploy-zip
          path: backend.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: deploy-zip

      - name: Unzip artifact
        run: unzip backend.zip

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2DEFA686FC874B8B9AFAEE3E47ED6316 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_8478C523B9C94B1BAFBABDDCC46DD3BD }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_22B582B9FB4B4169A2E0127B7479F829 }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'immoleaf-backend'
          slot-name: 'Production'
          package: .
