name: Deploy Immoleaf Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install & Build
        working-directory: backend
        run: |
          npm install
          npm run build || echo "No build step"

      - name: Prepare clean deployment folder
        run: |
          mkdir -p deploy
          cp -r backend/* deploy/

      - name: Zip deployment contents
        run: |
          cd deploy
          zip -r ../deploy.zip . -x "*.git*" "node_modules/*" "*.env" "*/__pycache__/*"

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'immoleaf-backend'
          slot-name: 'production'
          package: ./deploy.zip
