name: Deploy Immoleaf Backend to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Prepare clean deployment folder
        run: |
          mkdir deploy
          cp -r backend/index.js deploy/
          cp -r backend/package.json deploy/
          cp -r backend/package-lock.json deploy/ || true
          cp -r backend/dist deploy/dist || true

      - name: Install dependencies
        working-directory: deploy
        run: npm install

      - name: Create deployment zip
        run: |
          cd deploy
          zip -r ../deploy.zip .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'immoleaf-backend'
          slot-name: 'production'
          package: './deploy.zip'
