name: Deploy Frontend to Azure Web App - immoleaf-frontend

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/main_immoleaf-frontend.yml'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      - name: Build Vite frontend
        run: npm run build
        working-directory: ./frontend

      - name: Zip artifact for deployment
        run: cd dist && zip -r ../../release.zip .
        working-directory: ./frontend

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: release.zip

      - name: Download artifact for deployment
        uses: actions/download-artifact@v4
        with:
          name: frontend-dist
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'immoleaf-frontend'
          slot-name: 'Production'
          package: release.zip
