name: Deploy Immoleaf Backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'

      - name: Install & Build
        working-directory: backend
        run: |
          npm install
          npm run build || echo "no build step"

      - name: Upload artifact (backend contents only)
        run: |
          cd backend
          zip -r ../backend-content.zip .
      
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'immoleaf-backend'
          slot-name: 'Production'
          package: './backend-content.zip'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
